### ISSUE TITLE
CORS error

### ISSUE THREAD

**Issue by whatsdis** [stalgiag/p5.detect#2]
Access to image at 'file:///C:/Users/tester/Downloads/p5.detect-master/p5.detect-master/examples/text/arendt.png' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.

**Comment by stalgiag** [comment]
Hi @whatsdis this is due to the cors requirement of browsers. In order to run that [test locally you will need to run a local server.](https://github.com/processing/p5.js/wiki/Local-server) This is true whenever you work with images and p5.js. I also recommend giving [editor.p5js.org](https://editor.p5js.org/) a try. Closing this now for organization purposes as it isn't due to this library.
